### Numpy Exercises

#### No. 1

In [2]:
import numpy as np

#### No. 2

In [16]:
# Print the numpy version and the configuration
np.__version__
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anacon

#### No. 3

In [17]:
arr_1 = np.zeros(10)
arr_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

No. 4

In [18]:
arr_1.size
arr_1.nbytes

80

No. 5

In [27]:
# How to get the documentation of the numpy add function from the command line?
!pydoc numpy.add

Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the

No. 6

In [21]:
arr2 = np.zeros(10)
arr2[4] = 1
print(arr_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


No. 7

In [20]:
arr3 = np.arange(10, 50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

No. 8

In [24]:
# Reverse a vector
arr3 = arr3[::-1]
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

No. 9

In [25]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


No. 10

In [26]:
# 9. Find indices of non-zero elements from [1,2,0,0,4,0]
arr4 = np.nonzero([1,2,0,0,4,0])
arr4

(array([0, 1, 4], dtype=int64),)

No. 11

In [30]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

No. 12

In [31]:
# Create a 3x3x3 array with random values
arr5 = np.random.rand(3, 3, 3)
print(arr5)

[[[0.49829534 0.2692849  0.05720427]
  [0.21619655 0.77646548 0.84308117]
  [0.72725601 0.40934673 0.49214325]]

 [[0.9811063  0.78111182 0.32594145]
  [0.94597473 0.59491437 0.47675025]
  [0.93232742 0.83663207 0.31789959]]

 [[0.57359173 0.74682388 0.83593027]
  [0.07621484 0.25321446 0.85903113]
  [0.33635035 0.92618428 0.91914722]]]


No. 13

In [36]:
# Create a 10x10 array with random values and find the minimum and maximum values
arr6 = np.random.rand(10, 10)
print(arr6)
print("Minimum:", np.min(arr6))
print("Maximum:", np.max(arr6))

[[0.14016264 0.81540237 0.3084884  0.81419493 0.62582366 0.04660105
  0.49433614 0.34046253 0.12643892 0.36525771]
 [0.18009972 0.37398292 0.09929006 0.22440077 0.09718816 0.72028914
  0.86776104 0.73282805 0.57004597 0.08686318]
 [0.7679932  0.07872325 0.75296554 0.57861164 0.80447399 0.31652543
  0.02788051 0.77190545 0.66893666 0.50350574]
 [0.100158   0.74606612 0.90495915 0.39131846 0.2077369  0.29216955
  0.72100543 0.11483802 0.22970533 0.63484218]
 [0.40111679 0.72765709 0.7499722  0.3333706  0.9071306  0.88890257
  0.00574626 0.29915303 0.40687263 0.26476554]
 [0.70083576 0.89835641 0.14860146 0.70039205 0.17103222 0.10776395
  0.84839007 0.33592229 0.72669695 0.22688397]
 [0.60853308 0.31250088 0.40858528 0.86214642 0.18512632 0.5623952
  0.76905105 0.7764991  0.75772145 0.28517831]
 [0.45741718 0.30170751 0.13710082 0.7777656  0.50460206 0.30951424
  0.98008877 0.88112673 0.50854923 0.67565352]
 [0.85150568 0.04701197 0.06828903 0.64533457 0.69913069 0.3176109
  0.34303896 0

No. 14

In [43]:
# Create a random vector of size 30 and find the mean value
arr7 = np.random.rand(30)
print("Mean:", np.mean(arr7))

Mean: 0.47903042231484666


No. 15

In [42]:
# Create a 2d array with 1 on the border and 0 inside
arr8 = np.ones((4, 4))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


No. 16

In [44]:
# Define an existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the shape of the existing array
rows, cols = existing_array.shape

# Create a new array with increased dimensions (adding 2 to both rows and columns for the border)
new_rows = rows + 2
new_cols = cols + 2

# Create a new array filled with zeros with the increased dimensions
new_array = np.zeros((new_rows, new_cols), dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[1:-1, 1:-1] = existing_array

print("Existing array:")
print(existing_array)

print("\nArray with border of zeros:")
print(new_array)

Existing array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with border of zeros:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


No. 17

In [45]:
# 0 * np.nan
result1 = 0 * np.nan

# np.nan == np.nan
result2 = np.nan == np.nan

# np.inf > np.nan
result3 = np.inf > np.nan

# np.nan - np.nan
result4 = np.nan - np.nan

# np.nan in set([np.nan])
result5 = np.nan in set([np.nan])

# 0.3 == 3 * 0.1
result6 = 0.3 == 3 * 0.1

print("Result 1:", result1)
print("Result 2:", result2)
print("Result 3:", result3)
print("Result 4:", result4)
print("Result 5:", result5)
print("Result 6:", result6)

Result 1: nan
Result 2: False
Result 3: False
Result 4: nan
Result 5: True
Result 6: False


No. 18

In [48]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix_5x5 = np.diag(1 + np.arange(4), k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


No. 19

In [50]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
arr_8x8 = np.zeros((8, 8), dtype=int)
arr_8x8[1::2, ::2] = 1
arr_8x8[::2, 1::2] = 1
print(arr_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 20

In [54]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr10 = (6, 7, 8)
index_100 = np.unravel_index(100, arr10)
print("Index of the 100th element:", index_100)

Index of the 100th element: (1, 5, 4)


No. 21

In [56]:
# Create a checkerboard 8x8 matrix using the tile function
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 22

In [61]:
# Normalize a 5x5 random matrix
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - np.mean(random_matrix_5x5)) / np.std(random_matrix_5x5)
print(normalized_matrix)

[[ 1.15644809 -0.72776062  1.50126707  0.44792556 -0.68044575]
 [ 0.14060052  1.68271063 -0.64263086 -0.02979589  1.04864051]
 [-1.24180579 -0.94716129 -0.65471693 -0.77100398  0.30389194]
 [-0.93516396 -0.86630862  1.77549922 -1.1359365   0.29382427]
 [-0.45385015  0.98035722 -1.25401862  1.70739724 -0.69796332]]


No. 23

In [62]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('R', np.ubyte),
                        ('G', np.ubyte),
                        ('B', np.ubyte),
                        ('A', np.ubyte)])
print("\nCustom dtype for RGBA color:", color_dtype)


Custom dtype for RGBA color: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


No. 24

In [64]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_5x3 = np.random.randint(0, 10, (5, 3))
matrix_3x2 = np.random.randint(0, 10, (3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("\nProduct of 5x3 and 3x2 matrices:")
print(product_matrix)


Product of 5x3 and 3x2 matrices:
[[38 34]
 [77 63]
 [11 13]
 [53 59]
 [73 47]]


No. 25

In [65]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
array_1d = np.arange(11)
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
print("\nNegated elements between 3 and 8:")
print(array_1d)


Negated elements between 3 and 8:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### No. 26

In [68]:
# What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### No. 27

In [77]:
# Consider an integer vector Z, which of these expressions are legal?
print('Z**Z = Legal')
print('2 << Z >> 2 = Legal')
print('Z <- Z = Legal')
print('1j*Z = Legal')
print('Z/1/1 = Legal')
print('Z<Z>Z = Illegal')

Z**Z = Legal
2 << Z >> 2 = Legal
Z <- Z = Legal
1j*Z = Legal
Z/1/1 = Legal
Z<Z>Z = Illegal


#### No. 28

In [79]:
# What are the result of the following expressions?
result1 = np.array(0) / np.array(0)
result2 = np.array(0) // np.array(0)
result3 = np.array([np.nan]).astype(int).astype(float)
print("Result of np.array(0) / np.array(0):", result1)
print("Result of np.array(0) // np.array(0):", result2)
print("Result of np.array([np.nan]).astype(int).astype(float):", result3)

Result of np.array(0) / np.array(0): nan
Result of np.array(0) // np.array(0): 0
Result of np.array([np.nan]).astype(int).astype(float): [-2.14748365e+09]


C:\Users\FAISAL\AppData\Local\Temp\ipykernel_5372\4103880733.py:2: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)
C:\Users\FAISAL\AppData\Local\Temp\ipykernel_5372\4103880733.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  result2 = np.array(0) // np.array(0)
C:\Users\FAISAL\AppData\Local\Temp\ipykernel_5372\4103880733.py:4: RuntimeWarning: invalid value encountered in cast
  result3 = np.array([np.nan]).astype(int).astype(float)


In [80]:
# 29. How to round away from zero a float array?
arr = np.array([-1.5, 1.5, -2.5, 2.5])
rounded_arr = np.where(arr > 0, np.ceil(arr), np.floor(arr))
print("Rounded away from zero float array:", rounded_arr)

Rounded away from zero float array: [-2.  2. -3.  3.]


In [81]:
# 30. How to find common values between two arrays?
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common values between two arrays:", common_values)

Common values between two arrays: [3 4 5]


In [82]:
# 31. How to ignore all numpy warnings (not recommended)?
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [83]:
# 32. Is the following expression true?
result4 = np.sqrt(-1) == np.emath.sqrt(-1)
print("Is np.sqrt(-1) equal to np.emath.sqrt(-1)?", result4)

Is np.sqrt(-1) equal to np.emath.sqrt(-1)? False


In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

In [84]:
# 34. How to get all the dates corresponding to the month of July 2016?
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Dates corresponding to July 2016:", dates_july_2016)

Dates corresponding to July 2016: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [85]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
np.multiply(np.add(A, B), np.negative(A) / 2, out=A)
print("Result of ((A+B)*(-A/2)) in place:", A)

Result of ((A+B)*(-A/2)) in place: [[-0.06873673 -0.22198714 -0.26612035]
 [-0.00526683 -0.03968415 -0.02842758]
 [-0.60016021 -0.02490394 -0.49051077]]


In [86]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods
random_array = np.random.uniform(0, 10, 5)
integer_part_method1 = random_array - random_array % 1
integer_part_method2 = np.floor(random_array)
integer_part_method3 = np.ceil(random_array) - 1
integer_part_method4 = random_array.astype(int)
print("Integer part using method 1:", integer_part_method1)
print("Integer part using method 2:", integer_part_method2)
print("Integer part using method 3:", integer_part_method3)
print("Integer part using method 4:", integer_part_method4)

Integer part using method 1: [0. 5. 7. 0. 8.]
Integer part using method 2: [0. 5. 7. 0. 8.]
Integer part using method 3: [0. 5. 7. 0. 8.]
Integer part using method 4: [0 5 7 0 8]


In [87]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4
matrix_5x5 = np.zeros((5, 5))
matrix_5x5 += np.arange(5)
print("Matrix with row values ranging from 0 to 4:")
print(matrix_5x5)

Matrix with row values ranging from 0 to 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [88]:
# 38. Consider a generator function that generates 10 integers and use it to build an array
def generator():
    for i in range(10):
        yield i

array_from_generator = np.fromiter(generator(), dtype=int)
print("Array built from generator:", array_from_generator)

Array built from generator: [0 1 2 3 4 5 6 7 8 9]


In [89]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector_0_to_1_excluded = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print("Vector ranging from 0 to 1 (both excluded):", vector_0_to_1_excluded)

Vector ranging from 0 to 1 (both excluded): [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [90]:
# 40. Create a random vector of size 10 and sort it
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("Sorted random vector of size 10:", sorted_vector)

Sorted random vector of size 10: [0.03402676 0.23134805 0.28625616 0.39650211 0.40180663 0.4866724
 0.80349215 0.85078788 0.86158277 0.97516499]


In [91]:
# 41. How to sum a small array faster than np.sum?
# For a small array, using the built-in Python sum function is usually faster than np.sum.
small_array = np.arange(100)
sum_fast = np.sum(small_array)
sum_python = sum(small_array)
print("Sum using np.sum:", sum_fast)
print("Sum using Python's sum function:", sum_python)

Sum using np.sum: 4950
Sum using Python's sum function: 4950


In [92]:
# 42. Consider two random array A and B, check if they are equal
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
equal_check = np.array_equal(A, B)
print("Are arrays A and B equal?", equal_check)

Are arrays A and B equal? False


In [93]:
# 43. Make an array immutable (read-only)
immutable_array = np.zeros(5)
immutable_array.flags.writeable = False
# Trying to modify the array will raise a ValueError
# immutable_array[0] = 1

In [94]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
cartesian_coordinates = np.random.random((10, 2))
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print("Polar coordinates:")
print(polar_coordinates)

Polar coordinates:
[[0.26829848 0.7029469 ]
 [0.79227278 1.3784005 ]
 [0.4793397  0.984289  ]
 [0.58367725 1.00441968]
 [0.81399464 0.35272363]
 [0.81418896 1.44903637]
 [0.69842591 0.23288658]
 [0.49377449 0.19433733]
 [0.6218503  0.96638599]
 [0.99587459 0.82588825]]


In [95]:
# 45. Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.random(10)
random_vector[random_vector.argmax()] = 0
print("Random vector with maximum value replaced by 0:", random_vector)

Random vector with maximum value replaced by 0: [0.76844085 0.49082679 0.37500094 0.1742442  0.81748365 0.20244087
 0.55875892 0.         0.40647074 0.02996137]


In [96]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
structured_array = np.zeros((10, 10), [('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 10),
                                                          np.linspace(0, 1, 10))
print("Structured array with x and y coordinates:")
print(structured_array)

Structured array with x and y coordinates:
[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.3

In [97]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.random.rand(3)
Y = np.random.rand(3)
C = 1 / (X[:, None] - Y)
print("Cauchy matrix C:")
print(C)

Cauchy matrix C:
[[  2.62678291 -14.82459987   1.90739474]
 [ -3.39153827  -1.34589373  -6.61069863]
 [ -9.49024986  -1.80661762  26.17101496]]


In [101]:
# 48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print("Minimum and maximum representable value for", dtype)
    info = np.iinfo(dtype)
    print("Minimum:", info.min)
    print("Maximum:", info.max)

Minimum and maximum representable value for <class 'numpy.int8'>
Minimum: -128
Maximum: 127
Minimum and maximum representable value for <class 'numpy.int32'>
Minimum: -2147483648
Maximum: 2147483647
Minimum and maximum representable value for <class 'numpy.int64'>
Minimum: -9223372036854775808
Maximum: 9223372036854775807


In [105]:
# 49. How to print all the values of an array?
# Create an example array
arr11 = np.arange(100)

np.set_printoptions(threshold=np.inf)
print(arr11)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [106]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
import numpy as np

# Create a vector
vector = np.array([1, 2, 3, 4, 5])

# Given scalar
scalar = 3.5

# Find the index of the element with the closest value to the scalar
closest_index = np.argmin(np.abs(vector - scalar))

# Get the closest value
closest_value = vector[closest_index]

print("Closest value to", scalar, "in the vector is:", closest_value)


Closest value to 3.5 in the vector is: 3


In [107]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)
dtype = [('position', [('x', float), ('y', float)]),
         ('color',    [('r', int), ('g', int), ('b', int)])]
structured_array = np.zeros(1, dtype=dtype)
structured_array['position']['x'] = 1.0
structured_array['position']['y'] = 2.0
structured_array['color']['r'] = 255
structured_array['color']['g'] = 0
structured_array['color']['b'] = 0
print("Structured array representing position and color:")
print(structured_array)

Structured array representing position and color:
[((1., 2.), (255, 0, 0))]


In [108]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
random_vector = np.random.random((100, 2))
distances = np.linalg.norm(random_vector[:, None] - random_vector, axis=-1)
print("Distances between points:")
print(distances)

Distances between points:
[[0.         0.66626564 0.66239244 0.47539266 0.40759986 0.53166649
  0.36738387 0.67133449 0.23979506 0.53755162 0.27764128 0.63118604
  0.10502079 0.2557058  0.86141169 0.16280763 0.15548573 0.90269727
  0.47879797 0.17303223 0.68155692 0.53968523 0.46403611 0.30576677
  0.14841052 0.88118007 0.54429485 0.48625195 0.71820039 0.38174987
  0.75169913 0.49407403 0.11037902 0.49654194 0.77362561 0.59294018
  0.24846483 0.85377866 0.37725477 0.15785098 0.42931035 0.59428745
  0.74581483 0.80570898 0.29308205 0.79196584 0.3949962  0.67095442
  0.73464501 0.55183124 0.25795825 0.20771636 0.58679278 0.4260303
  0.32959929 0.33095301 0.67724349 0.52144352 0.62744683 0.85339117
  0.67342795 0.41281107 0.17273397 0.77555183 0.62131544 0.67340514
  0.61588541 0.36956854 0.50550575 0.55401657 0.50779981 0.87826958
  0.55206166 0.41203321 0.75448435 0.54809041 0.43422765 0.22054915
  0.80457245 0.19942259 0.6138939  0.60442026 0.37542831 0.58206818
  0.59665572 0.65056332

In [109]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
float_array = np.random.rand(10).astype(np.float32)
integer_array = float_array.view(np.int32)
print("Float array converted to integer array in place:")
print(integer_array)

Float array converted to integer array in place:
[1040371245 1060982743 1050658459 1059844109 1061678461 1060836100
 1050327014 1059925556 1062691770 1041430581]


In [112]:
# 54. How to read the following file?
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11
'''by using data = np.genfromtxt('file.txt', delimiter=',')
print("Data read from the file:")
print(data)'''

'by using data = np.genfromtxt(\'file.txt\', delimiter=\',\')\nprint("Data read from the file:")\nprint(data)'

In [113]:
# 55. What is the equivalent of enumerate for numpy arrays?
# The equivalent of enumerate for numpy arrays is np.ndenumerate.
array = np.array([[1, 2], [3, 4]])
for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [114]:
# 56. Generate a generic 2D Gaussian-like array
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ))
print("2D Gaussian-like array:")
print(gaussian_array)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

In [115]:
# 57. How to randomly place p elements in a 2D array?
p = 5
array_2d = np.zeros((10, 10))
np.put(array_2d, np.random.choice(range(10*10), p, replace=False), 1)
print("2D array with randomly placed elements:")
print(array_2d)

2D array with randomly placed elements:
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [116]:
# 58. Subtract the mean of each row of a matrix
matrix = np.random.rand(3, 3)
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print("Matrix with mean of each row subtracted:")
print(mean_subtracted_matrix)

Matrix with mean of each row subtracted:
[[-0.55052694  0.31218635  0.23834059]
 [ 0.15449019  0.07010616 -0.22459635]
 [-0.3167658   0.40082626 -0.08406046]]


In [117]:
# 59. How to sort an array by the nth column?
array = np.random.randint(0, 10, (5, 5))
n = 2
sorted_array = array[array[:, n].argsort()]
print("Array sorted by the nth column:")
print(sorted_array)

Array sorted by the nth column:
[[0 1 0 6 6]
 [8 8 2 0 3]
 [9 2 4 7 3]
 [0 0 6 0 6]
 [0 7 7 6 3]]


In [118]:
# 60. How to tell if a given 2D array has null columns?
array = np.array([[1, 0, 3], [0, 0, 0], [4, 0, 6]])
has_null_columns = np.any(np.all(array == 0, axis=0))
print("Does the given 2D array have null columns?", has_null_columns)

Does the given 2D array have null columns? True


In [119]:
# 61. Find the nearest value from a given value in an array
array = np.random.rand(10)
given_value = 0.5
nearest_value = array[(np.abs(array - given_value)).argmin()]
print("Nearest value from", given_value, "in the array:", nearest_value)

Nearest value from 0.5 in the array: 0.49698288925448697


In [120]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
array1 = np.arange(3).reshape(1, 3)
array2 = np.arange(3).reshape(3, 1)
iterator = np.nditer([array1, array2, None])
for a, b, c in iterator:
    c[...] = a + b
print("Sum of arrays computed using an iterator:")
print(iterator.operands[2])

Sum of arrays computed using an iterator:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [121]:
# 63. Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="Unnamed"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "Unnamed")

# Test the NamedArray class
array = NamedArray(np.arange(10), name="TestArray")
print("Array name:", array.name)

Array name: TestArray


In [122]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
vector = np.random.rand(10)
indices = np.random.randint(0, len(vector), 20)
np.add.at(vector, indices, 1)
print("Vector with 1 added to elements indexed by another vector:")
print(vector)

Vector with 1 added to elements indexed by another vector:
[2.612715   1.61121692 4.5950197  3.37317584 1.23016914 1.75289695
 3.60884004 3.81736665 0.24521702 2.84724   ]


In [124]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = np.array([1, 2, 3, 4, 5])
I = np.array([1, 3, 9, 3, 4])
F = np.bincount(I, X)
print("Accumulated elements of vector X based on index list I:")
print(F)

Accumulated elements of vector X based on index list I:
[0. 1. 0. 6. 5. 0. 0. 0. 0. 3.]


In [125]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 100, 100
image = np.random.randint(0, 256, (w, h, 3)).astype(np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print("Number of unique colors in the image:", unique_colors)

Number of unique colors in the image: 9999


In [126]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?
array = np.random.randint(0, 10, (3, 3, 3, 3))
sum_last_two_axes = array.sum(axis=(-2, -1))
print("Sum over the last two axes of the array:")
print(sum_last_two_axes)

Sum over the last two axes of the array:
[[45 40 41]
 [41 43 27]
 [19 35 36]]


In [127]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
means = np.bincount(S, weights=D) / np.bincount(S)
print("Means of subsets of vector D using vector S:")
print(means)

Means of subsets of vector D using vector S:
[0.41509436 0.45082721 0.54459991 0.62141607 0.50009727 0.40345104
 0.50618815 0.51819144 0.57827537 0.58903511]


In [128]:
# 69. How to get the diagonal of a dot product?
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)
print("Diagonal of the dot product:")
print(diagonal)

Diagonal of the dot product:
[18  2 63]


In [129]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) + (len(vector) - 1) * 3, dtype=vector.dtype)
new_vector[::4] = vector
print("New vector with 3 consecutive zeros interleaved between each value:")
print(new_vector)

New vector with 3 consecutive zeros interleaved between each value:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [130]:
# 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?
array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)
result = array1 * array2[:,:,None]
print("Result of multiplication:")
print(result)

Result of multiplication:
[[[0.07401863 0.09862603 0.07029123]
  [0.29594887 0.20793695 0.05546813]
  [0.12011127 0.72618987 0.44725178]
  [0.20851578 0.28064413 0.30034334]
  [0.11213655 0.32944727 0.14903299]]

 [[0.77415445 0.05190669 0.00554382]
  [0.85536637 0.85498839 0.44226839]
  [0.45733105 0.43250878 0.48611981]
  [0.43697553 0.08727994 0.14724762]
  [0.09814728 0.06440277 0.08909462]]

 [[0.47283387 0.45868699 0.21320883]
  [0.38351265 0.23722424 0.39103537]
  [0.48102333 0.25224382 0.0406158 ]
  [0.09939747 0.20275107 0.10221123]
  [0.07728164 0.18482318 0.12262812]]

 [[0.00822241 0.07202594 0.04757092]
  [0.49145767 0.59710623 0.54394011]
  [0.48582831 0.4515715  0.27171368]
  [0.13475974 0.02896003 0.02186888]
  [0.15221602 0.11568436 0.1042583 ]]

 [[0.24379813 0.09623343 0.16417752]
  [0.25761012 0.19328442 0.365951  ]
  [0.37531531 0.143868   0.06963685]
  [0.09982944 0.02166933 0.03466633]
  [0.22972747 0.16894688 0.09300447]]]


In [131]:
# 72. How to swap two rows of an array?
array = np.random.randint(0, 10, (5, 5))
array[[0, 1]] = array[[1, 0]]
print("Array with two rows swapped:")
print(array)

Array with two rows swapped:
[[6 5 4 1 9]
 [5 1 9 8 0]
 [0 6 7 7 3]
 [7 4 0 7 6]
 [2 2 7 7 9]]


In [132]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
triplets = np.random.randint(0, 100, (10, 3))
lines = np.roll(triplets.repeat(2,axis=1),-1,axis=1)
lines = np.sort(lines.reshape(len(lines)*3,2),axis=1)
unique_lines = np.unique(lines, axis=0)
print("Set of unique line segments:")
print(unique_lines)

Set of unique line segments:
[[ 1 11]
 [ 1 89]
 [ 7 16]
 [ 7 28]
 [11 89]
 [12 29]
 [12 86]
 [16 28]
 [16 75]
 [16 97]
 [21 46]
 [21 64]
 [24 36]
 [24 51]
 [29 86]
 [36 51]
 [39 90]
 [39 95]
 [46 64]
 [49 72]
 [49 92]
 [65 84]
 [65 87]
 [65 89]
 [65 96]
 [72 92]
 [75 97]
 [84 96]
 [87 89]
 [90 95]]


In [133]:
# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print("Array A such that np.bincount(A) == C:")
print(A)

Array A such that np.bincount(A) == C:
[1 1 2 3 4 4 6]


In [135]:
# 75. How to compute averages using a sliding window over an array?
def sliding_window_average(arr, window_size):
    cumsum = np.cumsum(arr)
    cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
    return cumsum[window_size - 1:] / window_size

arr = np.arange(20)
window_size = 3
averages = sliding_window_average(arr, window_size)
print("Averages using a sliding window over the array:")
print(averages)

Averages using a sliding window over the array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [134]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
def shift_array(arr, shift):
    return np.vstack([np.roll(arr, -i) for i in range(shift)])

Z = np.arange(15)
result = shift_array(Z, 3)
print("Two-dimensional array built from the one-dimensional array:")
print(result)

Two-dimensional array built from the one-dimensional array:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14  0]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14  0  1]]


In [136]:
# 77. How to negate a boolean, or to change the sign of a float inplace?
boolean_array = np.random.choice([True, False], 10)
float_array = np.random.rand(10)
np.logical_not(boolean_array, out=boolean_array)
np.negative(float_array, out=float_array)
print("Negated boolean array:")
print(boolean_array)
print("Float array with changed signs:")
print(float_array)

Negated boolean array:
[ True False False False  True  True  True  True  True False]
Float array with changed signs:
[-0.11743459 -0.1460476  -0.27842611 -0.81402606 -0.40854247 -0.14562596
 -0.59283929 -0.42713626 -0.90260564 -0.11850996]


In [137]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
P0 = np.random.rand(5, 2)
P1 = np.random.rand(5, 2)
p = np.random.rand(2)
distances = np.abs(np.cross(P1 - P0, P0 - p) / np.linalg.norm(P1 - P0, axis=1))
print("Distances from point p to each line:")
print(distances)

Distances from point p to each line:
[0.39611207 0.21091805 0.16126984 0.0014166  0.04928084]


In [138]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P = np.random.rand(5, 2)
distances = np.zeros((len(P), len(P0)))
for i in range(len(P0)):
    distances[:, i] = np.abs(np.cross(P1[i] - P0[i], P0[i] - P) / np.linalg.norm(P1[i] - P0[i]))
print("Distances from each point to each line:")
print(distances)

Distances from each point to each line:
[[0.17603326 0.01073254 0.31887091 0.07057805 0.65523947]
 [0.60177011 0.10069437 0.28341893 0.14666535 0.27677957]
 [0.07046068 0.52508948 0.15869521 0.32715791 0.10858273]
 [0.51942838 0.18893606 0.53698721 0.32413542 0.29801941]
 [0.41796002 0.08957982 0.43596308 0.22072211 0.34508445]]


In [140]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
def extract_subpart(arr, shape, center, fill_value):
    # Convert inputs to NumPy arrays
    arr = np.array(arr)
    shape = np.array(shape)

    # Calculate the starting and ending indices for each dimension
    start = np.maximum(center - shape // 2, 0)
    end = np.minimum(start + shape, arr.shape)

    # Create an empty array with the desired shape and fill it with the fill value
    subpart = np.full(shape, fill_value)

    # Calculate the indices for the subpart within the full array
    subpart_start = start - (center - shape // 2)
    subpart_end = subpart_start + (end - start)

    # Copy the relevant portion from the full array to the subpart array
    subpart[subpart_start[0]:subpart_end[0], subpart_start[1]:subpart_end[1]] = arr[start[0]:end[0], start[1]:end[1]]

    return subpart

In [141]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))
print("Array R:")
print(R)

Array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [142]:
# 82. Compute a matrix rank
matrix = np.random.rand(3, 3)
rank = np.linalg.matrix_rank(matrix)
print("Matrix rank:", rank)

Matrix rank: 3


In [143]:
# 83. How to find the most frequent value in an array?
array = np.random.randint(0, 10, 20)
most_frequent_value = np.bincount(array).argmax()
print("Most frequent value in the array:", most_frequent_value)

Most frequent value in the array: 4


In [144]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))
print("Contiguous 3x3 blocks from the matrix:")
print(blocks)

Contiguous 3x3 blocks from the matrix:
[[[[9 0 9]
   [4 3 3]
   [3 7 6]]

  [[0 9 6]
   [3 3 2]
   [7 6 4]]

  [[9 6 0]
   [3 2 4]
   [6 4 9]]

  [[6 0 6]
   [2 4 9]
   [4 9 6]]

  [[0 6 9]
   [4 9 5]
   [9 6 4]]

  [[6 9 8]
   [9 5 9]
   [6 4 2]]

  [[9 8 8]
   [5 9 1]
   [4 2 9]]

  [[8 8 7]
   [9 1 5]
   [2 9 0]]]


 [[[4 3 3]
   [3 7 6]
   [8 5 4]]

  [[3 3 2]
   [7 6 4]
   [5 4 7]]

  [[3 2 4]
   [6 4 9]
   [4 7 5]]

  [[2 4 9]
   [4 9 6]
   [7 5 5]]

  [[4 9 5]
   [9 6 4]
   [5 5 7]]

  [[9 5 9]
   [6 4 2]
   [5 7 2]]

  [[5 9 1]
   [4 2 9]
   [7 2 5]]

  [[9 1 5]
   [2 9 0]
   [2 5 1]]]


 [[[3 7 6]
   [8 5 4]
   [8 7 6]]

  [[7 6 4]
   [5 4 7]
   [7 6 9]]

  [[6 4 9]
   [4 7 5]
   [6 9 2]]

  [[4 9 6]
   [7 5 5]
   [9 2 9]]

  [[9 6 4]
   [5 5 7]
   [2 9 0]]

  [[6 4 2]
   [5 7 2]
   [9 0 3]]

  [[4 2 9]
   [7 2 5]
   [0 3 3]]

  [[2 9 0]
   [2 5 1]
   [3 3 2]]]


 [[[8 5 4]
   [8 7 6]
   [1 3 7]]

  [[5 4 7]
   [7 6 9]
   [3 7 7]]

  [[4 7 5]
   [6 9 2]
   [7 7 0]]

  [[7 5 5]

In [148]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

    def __getitem__(self, index):
        i, j = index
        return super().__getitem__((i, j))

Z = SymmetricArray((5, 5))
Z[1, 2] = 5  # Now Z[2, 1] will also be set to 5
print("SymmetricArray:")
print(Z)

SymmetricArray:
[[0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [149]:
# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)
result = np.einsum('ijk,ikl->jl', matrices, vectors)
print("Sum of the p matrix products:")
print(result)

Sum of the p matrix products:
[[2.45575749]
 [2.44287543]
 [3.25967461]
 [3.21228406]]


In [150]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
array = np.random.rand(16, 16)
block_size = 4
block_sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], block_size), axis=0),
                            np.arange(0, array.shape[1], block_size), axis=1)
print("Block-sum of the array:")
print(block_sum)

Block-sum of the array:
[[ 8.86961976  7.73104191  7.32798608  8.34742209]
 [ 8.23375937  8.80311342  7.38777307  9.62509532]
 [ 7.57079467  6.44365883  9.27526499  8.11174541]
 [ 7.66678232  6.78286034 10.12966799  8.30889125]]


In [152]:
# 88. How to implement the Game of Life using numpy arrays?
def iterate_game_of_life(grid):
    # Count neighbors
    neighbors = sum(np.roll(np.roll(grid, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
    # Apply rules
    return (neighbors == 3) | (grid & (neighbors == 2))

# testing
grid = np.random.choice([0, 1], (50, 50))
for _ in range(100):
    grid = iterate_game_of_life(grid)
print("Final state of the Game of Life grid:")
print(grid)

Final state of the Game of Life grid:
[[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0

C:\Users\FAISAL\AppData\Local\Temp\ipykernel_5372\2932595884.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  neighbors = sum(np.roll(np.roll(grid, i, 0), j, 1)


In [153]:
# 89. How to get the n largest values of an array
array = np.random.rand(100)
n = 5
largest_values_indices = array.argsort()[-n:]
print("Indices of the n largest values:", largest_values_indices)
print("n largest values:", array[largest_values_indices])

Indices of the n largest values: [84  6 60 87 96]
n largest values: [0.93940532 0.97280445 0.97820169 0.9805617  0.99081962]


In [154]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
vectors = [np.array([1, 2]), np.array([3, 4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print("Cartesian product of the vectors:")
print(cartesian_product)

Cartesian product of the vectors:
[[1 3 6]
 [1 4 6]
 [1 5 6]
 [2 3 6]
 [2 4 6]
 [2 5 6]
 [1 3 7]
 [1 4 7]
 [1 5 7]
 [2 3 7]
 [2 4 7]
 [2 5 7]]


In [155]:
# 91. How to create a record array from a regular array?
regular_array = np.array([(1, 2.0, 'Hello'), (3, 4.0, 'World')], dtype=[('A', int), ('B', float), ('C', 'U10')])
record_array = np.core.records.fromarrays(regular_array.T, names='A, B, C')
print("Record array from a regular array:")
print(record_array)

Record array from a regular array:
((1, 2., 'Hello'), (3, 4., 'World'))


In [156]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
Z = np.random.rand(10000)
method1 = np.power(Z, 3)
method2 = Z * Z * Z
method3 = np.einsum('i,i,i->i', Z, Z, Z)
print("Result using method 1:", method1)
print("Result using method 2:", method2)
print("Result using method 3:", method3)

Result using method 1: [4.65127025e-01 9.26306894e-02 2.93908784e-03 1.10920166e-02
 6.78618723e-01 9.46962173e-01 4.85988406e-01 4.00338198e-01
 3.51877671e-02 3.60615703e-01 3.84974172e-02 2.46724822e-05
 2.71073689e-01 4.35503579e-01 8.15722969e-03 5.22560692e-08
 4.41251319e-02 4.53552472e-02 1.59891379e-01 9.45733124e-01
 3.70320482e-04 3.69949624e-02 1.05780338e-01 6.80317779e-07
 3.52478292e-01 7.95697240e-01 5.68833842e-02 1.55089236e-02
 7.44118428e-01 6.95565767e-01 3.07208464e-01 5.32192777e-02
 5.89886068e-04 1.81195779e-04 1.77743693e-04 4.23101760e-03
 7.69492627e-04 2.40993923e-01 2.42059951e-01 6.58989460e-02
 1.44140984e-02 1.70161566e-03 8.10939242e-01 8.77651235e-01
 4.27983980e-02 2.27166329e-04 9.42659661e-02 3.10464465e-05
 1.94377494e-01 7.92090567e-01 3.50722780e-02 1.62533100e-01
 7.93503243e-03 3.57955874e-02 3.11040288e-01 3.26942006e-01
 9.47521688e-01 5.39347324e-06 1.14748745e-02 3.42573016e-03
 6.86444820e-02 2.39153868e-01 4.44001333e-02 1.44564650e-01
 

In [163]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 2, 9],
              [4, 6, 5],
              [7, 9, 8],
              [1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [4, 5]])

# Find rows of A that contain elements of each row of B
result1 = np.where(np.logical_and.reduce(np.isin(A, B), axis=1))[0]

print(result1)

[]


In [164]:
# 94. Considering a 10x3 matrix, extract rows with unequal values
matrix = np.random.randint(0, 5, (10, 3))
unequal_rows = matrix[np.any(np.diff(matrix, axis=1), axis=1)]
print("Rows with unequal values:")
print(unequal_rows)

Rows with unequal values:
[[1 2 2]
 [1 3 0]
 [3 4 4]
 [3 2 1]
 [0 2 1]
 [3 2 1]
 [3 1 4]
 [0 4 3]
 [4 0 2]
 [4 0 2]]


In [165]:
# 95. Convert a vector of ints into a matrix binary representation
vector = np.array([0, 1, 2, 3, 4, 5])
binary_matrix = ((vector[:, None] & (1 << np.arange(6))) > 0).astype(int)
print("Binary matrix representation:")
print(binary_matrix[:, ::-1])

Binary matrix representation:
[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 1]]


In [166]:
# 96. Given a two-dimensional array, how to extract unique rows?
array = np.random.randint(0, 5, (5, 3))
unique_rows = np.unique(array, axis=0)
print("Unique rows of the array:")
print(unique_rows)

Unique rows of the array:
[[0 0 3]
 [2 2 3]
 [2 3 0]
 [4 0 1]
 [4 4 4]]


In [167]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner = np.einsum('i,i->', A, B)
outer = np.einsum('i,j->ij', A, B)
sum_result = np.einsum('i->', A)
mul_result = np.einsum('i,i->i', A, B)
print("Einsum equivalent of inner:", inner)
print("Einsum equivalent of outer:")
print(outer)
print("Einsum equivalent of sum:", sum_result)
print("Einsum equivalent of mul:", mul_result)

Einsum equivalent of inner: 32
Einsum equivalent of outer:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Einsum equivalent of sum: 6
Einsum equivalent of mul: [ 4 10 18]


In [169]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
import scipy

X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7, 8])
distance = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
samples = np.zeros(len(X))
t = np.cumsum(np.r_[0, distance])
t /= t[-1]
interp_func = scipy.interpolate.interp1d(t, X)
x_interp = interp_func(np.linspace(0, 1, 10))
interp_func = scipy.interpolate.interp1d(t, Y)
y_interp = interp_func(np.linspace(0, 1, 10))

In [170]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees
n = 5
X = np.array([[1, 0, 3, 0], [2, 0, 1, 1], [1, 1, 2, 1], [0, 2, 1, 2], [1, 1, 1, 2]])
rows = np.array([np.all(np.bincount(row.astype(int)) == n) for row in X])
print("Rows which can be interpreted as draws from a multinomial distribution with", n, "degrees:")
print(X[rows])

Rows which can be interpreted as draws from a multinomial distribution with 5 degrees:
[]


In [171]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X
X = np.random.randn(1000)
N = 1000
indexes = np.random.randint(0, len(X), (N, len(X)))
means = X[indexes].mean(axis=1)
conf_intervals = np.percentile(means, [2.5, 97.5])
print("Bootstrapped 95% confidence intervals for the mean of X:", conf_intervals)

Bootstrapped 95% confidence intervals for the mean of X: [-0.02579607  0.09812201]
